[package]
name = "sllama"
version = "0.1.5"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
crossterm = { version = "0.29.0" }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
tempfile = "3.20.0"
rustyline = "16.0.0"
